add wishlist test case 3

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -75,25 +75,25 @@ jobs:
             pip install black~=23.0 flake8
             black --check .
 
-        # - name: Wait for DB to be ready
-        #   run: |
-        #     until pg_isready -h postgres -p 5432 -U postgres; do
-        #       echo "Waiting for postgres..."
-        #       sleep 1
-        #     done
-        - name: Wait for PostgreSQL to be fully ready
+        - name: Wait for DB to be ready
           run: |
-            echo "Waiting for PostgreSQL to accept connections and respond to queries..."
-            for i in {1..20}; do
-              PGPASSWORD=root psql -h postgres -U postgres -d shopping_db_2 -c '\q' && break
-              echo "PostgreSQL not ready yet... retrying ($i)"
-              sleep 2
+            until pg_isready -h postgres -p 5432 -U postgres; do
+              echo "Waiting for postgres..."
+              sleep 1
             done
+        # - name: Wait for PostgreSQL to be fully ready
+        #   run: |
+        #     echo "Waiting for PostgreSQL to accept connections and respond to queries..."
+        #     for i in {1..20}; do
+        #       PGPASSWORD=root psql -h postgres -U postgres -d shopping_db_2 -c '\q' && break
+        #       echo "PostgreSQL not ready yet... retrying ($i)"
+        #       sleep 2
+        #     done
 
-            if [ $i -eq 20 ]; then
-              echo "PostgreSQL did not become ready in time." >&2
-              exit 1
-            fi
+        #     if [ $i -eq 20 ]; then
+        #       echo "PostgreSQL did not become ready in time." >&2
+        #       exit 1
+        #     fi
  
         - name: Apply migrations
           run: |
